### ISSUE TITLE
How to use library in browser

### ISSUE THREAD

**Issue by dariobanfi** [bold-commerce/bold-subscriptions-js#3] opened 2020-05-12 17:41 UTC
Hi, I would like to use this library to integrate my Bold into my headless shopify but I cannot seem to understand the usage.
I have a custom frontend and communicate through the Storefront API.

1. If I use the library on the frontend (e.g. `cart.standard.addToCart({...})`), this will fail because of CORS since it tried a post to `cart.js` which does not allow it

2. If I use the library on the backend, then I need to get back the cookies from shopify and set them on the user browser under the correct domain in order for the `recurringcheckout.com` page to work, which is not possible.

Am I misunderstanding how to use it?

Thanks in advance!

**Comment by mlaigre** [comment] 2021-01-06 09:38
Hello,

@dariobanfi if subscriptions can't be used otherwise than using the cart.js API you are right this cannot be done with a headless Shopify

@Bold Team any hint on this ?

Thanks!

**Comment by game-of-morgan** [comment] 2021-05-30 23:14
Hi all,

So sorry for the delay in replies here. Since the inception of this library Bold has introduced and now matured the version 2 of our Subscriptions application. I myself have been working on that v2 for a while and am just seeing some of these comments.

I can confirm that this library does depend on the Shopify cart API which does have CORS limitations and thus would not work in a headless setting. That being said, I am now thinking about how I would rewrite this library for Bold Subscriptions v2 in a headless manner that still works with Shopify as well as Bold's checkout.

I will close this issue on that note but if am happy to take suggestions for improvements to this library still. Also glad to talk to any individual about some of the cool stuff we have done and have planned for the developer experience on BS2.

**Closed by game-of-morgan** 2021-05-30 23:14 UTC

**Comment by lamellama** [comment] 2021-11-05 14:07
> I will close this issue on that note but if am happy to take suggestions for improvements to this library still. Also glad to talk to any individual about some of the cool stuff we have done and have planned for the developer experience on BS2.

I have also run into this CORS situation with bold-subscriptions-js. And would like to hear about the BS2 solution
